// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[userId].tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/prompt.tsx";
import * as $$0 from "./islands/ProfileLoader.tsx";
import * as $$1 from "./islands/PromptGenerator.tsx";

const manifest = {
  routes: {
    "./routes/[userId].tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/prompt.tsx": $2,
  },
  islands: {
    "./islands/ProfileLoader.tsx": $$0,
    "./islands/PromptGenerator.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
